### ISSUE TITLE
There are several empty csv's with API redirect message

### ISSUE THREAD

**Issue by ucldsabs1** [COVID19Tracking/covid-tracking-data#101]

**Comment by johnrolfeellis** [comment]
The COVID19Tracking/covid-tracking-data repository is no longer supported. The Readme says:

"Do not use this repository to download or display data. Use the COVID Tracking API instead."

The CSVs are available in that repository, albeit with somewhat different names.

**Comment by julia326** [comment]
Hi there, this repo in general should not be used as the source of data truth - instead, please use our API at https://covidtracking.com/api.
