### ISSUE TITLE
[AL] Secondary screenshot should capture tab 11 of the dashboard

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/covid-tracking-data#105]
Please add a click on the number 11 `id="ember353"` before capturing the secondary screenshot. 

![image](https://user-images.githubusercontent.com/1749380/91309496-a9ddc380-e77e-11ea-9223-32486b0f0d8a.png)

**Comment by julia326** [comment]
Thank you! This should be fixed with the next screenshot (in about an hour and a half).

**Comment by muamichali** [comment]
Hi @julia326 

I am checking and I see tab 7 in the secondary screenshot rn. Can you look into it please?

https://covidtracking.com/screenshots/AL/AL-secondary-20200902-060418.png

**Comment by julia326** [comment]
Ah - unfortunately we're hitting the brittleness of referring to Ember elements in dashboards :/ they changed the element ID for tab 11. I just updated it now to what it is today, but this isn't a very stable solution.

**Comment by julia326** [comment]
Fixed this one again, but unfortunately it's brittle. It's a very unwieldy dashboard in general so I don't have a great solution yet but will keep paying attention to this one
