### ISSUE TITLE
[SC] primary source screenshot doesn't capture embedded dashboard

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/covid-tracking-data#108]
The screenshots for the [SC primary source](https://scdhec.gov/infectious-diseases/viruses/coronavirus-disease-2019-covid-19/sc-testing-data-projections-covid-19) never capture the embedded arcgis dashboard at the top with the case counts because it takes forever to load. See for instance https://covidtracking.com/screenshots/SC/SC-20200914-062847.png Is there any way it could have a 30-second timer on it or something so that the dashboard loads before the screenshot is taken?

**Comment by julia326** [comment]
Just added a 30-sec timer on it, should hopefully do the trick!

**Comment by amandafrench** [comment]
Beautiful, yay! https://covidtracking.com/screenshots/SC/SC-20200917-002717.png
