### ISSUE TITLE
Screenshot for states with multiple pages or press releases

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/covid-tracking-data#14]
Guam among other states issues individual press releases for all of their number, which means the single screenshot we're currently taking of their homepage carries little to no information to double check our data aside from occasional numbers in titles.

We should probably setup a process for individual states where we either screenshot `n + 1` page (homepage + detail page) (which is fairly common, even on dashboards and sometimes requires a click interaction to trigger because ARCGIS dashboards do not use the DOM [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) as they should to update the URL on separate tabs.

We also have situations where we have a central hub that links to individual press releases that either can't be predicted (non-sequential URLs for the individual press releases) and therefore require a click on the topmost item (assuming that item is a press release relevant to COVID, which may not always be the case).

**Comment by julia326** [comment]
Closing this issue out: it's partially solved (we capture secondary screenshots) and also to some extent is superceded by current work to set up other URLs to screenshot.
