### ISSUE TITLE
UTC Dates

### ISSUE THREAD

**Issue by kmatarese** [COVID19Tracking/covid-tracking-data#15]
First off thanks for doing this.

Have you given any thought to using UTC instead of EST for the dates? Is there a limitation in the data sources that would prevent that? There are a lot of interesting data sources and examples showing up, and unfortunately many are going in different directions for things like time zones and geo granularity.

**Comment by Nosferican** [comment]
You can get the timestamp in UTC. There seem to have been an old issue in the earlier days where the conversion from `America/New_York` to UTC had some issues. For that reason I use the timestamp with the time zone and convert it to UTC. The API does offer the timestamps in UTC so if you use the API you get those. The data backups have both the timestamp with the `America/New_York` timezone and the UTC timestamps.

**Comment by kmatarese** [comment]
The API page (https://covidtracking.com/api/) says the following:

> As you might be able to tell from the key names, date time values are in ET.

Also everything is at the date level from what I can see, so there would be no way to properly shift the dates (and stats) to start on each UTC day. Let me know if I'm missing something though!

**Comment by Nosferican** [comment]
Take a look at the data ([REST/states](https://covidtracking.com/api/states)), it has the following fields:
- `lastUpdateEt` (ET)
- `checkTimeEt` (ET)
- `dateModified` (UTC)
- `dateChecked` (UTC)
The GraphQL has dateChecked but it currently has an issue for `dateModified` if not mistaken.

See the API [backups](https://github.com/COVID19Tracking/covid-tracking-data/blob/master/data/states_daily_4pm_et.csv).

**Comment by kmatarese** [comment]
Sorry I wasn't clear -- I'm pulling your api/states/daily endpoint, and I'm interested in getting the numbers by UTC date rather than by ET date. That would allow properly marrying this data with other data global data sources such as the [JHU](https://github.com/CSSEGISandData/COVID-19) data. 

That said, the discrepancies the time zone issues cause are probably relatively minor. It would just be nice if all of the people out there doing great work to compile this stuff together (you guys, JHU, NYT, etc.) agreed on a set of baseline standards for common fields like geos and times.

**Comment by Nosferican** [comment]
I am not affiliated with the project. Should be trivial to convert from ET to UTC before linking with other data (we do so for our project after consuming the data from this project). I think the schema was hurried at first since it was very time sensitive to get it working but while doing our data discovery and profiling this project seemed the best in terms of documentation / qc / coverage and thought out data schema. I agree the it would best to always have the timestamp in UTC as a general rule for most projects.

**Comment by kmatarese** [comment]
OK, thanks for your consideration on this anyway.

FWIW, you can't just shift the date from ET to UTC and call it a day unless you had stats broken down by the hour in the time series.
