### ISSUE TITLE
Data not updating

### ISSUE THREAD

**Issue by rameezsadikot** [COVID19Tracking/covid-tracking-data#16]
Hi, 

Is there is a reason the google docs spreadsheet contains data as of the 29th, but the data in this repo is only as of the 27th? Ideally we'd love to be using the most current source, but the github repo is the easiest to work with from an automation perspective, so just wondering if we need to switch to the Google docs spreadsheet, or there is a plan to make sure the github repo stays current?

Thanks.

**Comment by julia326** [comment]
Sorry about that, resuming regular data updates now - I just updated the data in this repo. Will keep current to the Google docs spreadsheet going forward, with a delay of at most a few hours.

**Comment by rameezsadikot** [comment]
Thank you!

**Comment by thoo** [comment]
@rameezsadikot 
You could also do like this to update your csv files. 
```bash
curl https://covidtracking.com/api/states.csv -o states_current.csv
curl https://covidtracking.com/api/states/daily.csv -o states_daily_4pm_et.csv
curl https://covidtracking.com/api/states/info.csv -o states_info.csv
curl https://covidtracking.com/api/us.csv -o us_current.csv
curl https://covidtracking.com/api/us/daily.csv -o us_daily.csv
curl https://covidtracking.com/api/counties.csv -o counties.csv
```
