### ISSUE TITLE
License the data under a Creative Commons Zero license

### ISSUE THREAD

**Issue by kaldari** [COVID19Tracking/covid-tracking-data#18]
Right now this data is being licensed under the Apache license (same as the rest of the COVID19Tracking website). While the Apache license is great for software, it doesn't really make any sense for a data set (for example, there are no patent rights associated with data) and is likely incompatible with other licenses that are used for data, thus limiting people's ability to combine this data with other datasets. I would suggest licensing this specific repo under a Creative Commons license such as CC Attribution, CC0, or CC Attribution-ShareAlike. You could even dual license it under both Apache and a CC license if you wanted to (allowing the reuser to choose one license or the other).

**Comment by metasj** [comment]
You can update the subject to "License under CC-0".

**Todo**: move to CC-0, update the footers everywhere

**Comment by kaldari** [comment]
@metasj - Are you involved in this project?

**Comment by metasj** [comment]
Yes, and we could use a touch of kaldari

**Comment by julia326** [comment]
@metasj This repo is a mix of software and data - what would you recommend in this case, should we dual-license it?

**Comment by kaldari** [comment]
If it's software and data, it seems like dual licensing would be ideal.

**Comment by Nosferican** [comment]
Since the data was queried through the API, I believe it would fall under the EUA of the API, no?

**Comment by mlinksva** [comment]
It looks like this repo only has trivial software, and mostly data. I'd suggest just changing its license to CC0-1.0. Or do for this repo the same as for others...

The other repos could remain under Apache-2.0, with something like this in the footer of each noting that data is CC0-1.0:

```
### License

Code is released under [Apache-2.0](LICENSE).

Data and documentation is released under [CC0-1.0](https://creativecommons.org/publicdomain/zero/1.0/). If you use this material, you are encouraged but not required to cite [The COVID Tracking Project](https://covidtracking.com/) and to release your work that uses this material under an open license.
```

Or release everything, including code, under CC0-1.0!

For the website, perhaps just have a License footer linking to README#License or the same text on the website? And/or put in the site/API EUA which AFAICT doesn't exist now.

**Comment by Nosferican** [comment]
Thanks @mlinksva!

**Comment by julia326** [comment]
@metasj what's our policy here?

**Comment by kaldari** [comment]
@mlinksva's solution in the pull request looks good to me. We could also add some licensing info to the [API page](https://covidtracking.com/api), but that will need to be done in the [website repo](https://github.com/COVID19Tracking/website).

**Comment by metasj** [comment]
@julia326 catching up with this -- I like the approach of explicitly noting the license for code, and the license for data.  Mike's [proposed patch](https://github.com/COVID19Tracking/covid-tracking-data/pull/35/commits/133de8b7bff371ae9bdd215b1e48d14d702ec49c) looks good.

**Comment by kaldari** [comment]
@julia326 - What do you think about merging Mike's patch?

**Comment by kevee** [comment]
The official project's data license is here: https://covidtracking.com/license
We should add a header in the readme that covers "Data license."

**Comment by metasj** [comment]
That's quite the change; what was the reasoning behind it?  An NC license would be a definite loss for the community, and for federated public knowledge.  While the custom clauses added to the current license support one-off reuses in the context of single compilations / publications, it excludes the most common forms of reuse and remixing, including integration with Wikipedia, Wikidata, or other major crowdsourced datasets devoted to public health.

**Comment by zachlipton** [comment]
Just to belatedly close the loop on this, [the project's license](https://covidtracking.com/about-data/license) was changed to CC BY 4.0 quite some time ago.
