### ISSUE TITLE
Add a date column with date in a format readable by spreadsheets?

### ISSUE THREAD

**Issue by philgoetz** [COVID19Tracking/covid-tracking-data#24]
After importing any of the spreadsheets into Excel or Google Sheets, it's impossible for either Excel or Google Sheets to treat the date column like a date, because it's in a format that neither of those programs can recognize: 20200331 .  Neither can they recognize 200331.

This makes it impossible to use a spreadsheet to produce graphs with easily-readable and understandable date labels like "3/31" without converting all 1430 rows of the date column by hand.

**Comment by pbeerli** [comment]
does this help you:
https://www.excel-exercise.com/convert-date-yyyymmdd-to-dd-mm-yyyy-without-formula/

[I convert the date within python and actually really like the yearmonthday format

Peter

**Comment by philgoetz** [comment]
Yes, that did it!  Thank; I didn't know about the DATE function.

**Comment by Nosferican** [comment]
The API does give the timestamp in a more suitable format for parsing.

**Comment by AlanJayWeiner** [comment]
I'm importing the data into Google Sheets; this also works in Excel:

I convert the YYYYMMDD form into a date value using:
`=DATEVALUE(TEXT(B2, "####-##-##"))`

or to leave the cell empty if B2 doesn't have a date:
`=IF(B2, DATEVALUE(TEXT(B2, "####-##-##")), "")`

Both those leave a date value; I then format the cell to display the date however I wish.

**Comment by julia326** [comment]
Closing this out for now, as this seems like more of an API issue - please feel free to reopen though if I'm wrong!
