### ISSUE TITLE
Will this data collection stop as well in March?

### ISSUE THREAD

**Issue by GiorgiLomaia** [COVID19Tracking/covid-tracking-data#242]

**Comment by zachlipton** [comment]
Hi GiorgiLomaia. Thanks for asking!

This repository contains a lot of different types of data. Some of the files here will stop being updated after March 7th, including all the CSV backups of COVID Tracking Project data (e.g. `states_current.csv`, `states_daily_4pm_et.csv`, `us_daily.csv`, etc...)—the files here are just mirrors of [our API](https://covidtracking.com/data/api), and data collection for that will stop next month. But this repository also has archives of government COVID data (e.g. all the CDC and HHS files) and scripts that update this data regularly. Those federal data archiving scripts will continue to run after March 7th , though I can't promise a specific period beyond that when they'll be maintained. We will provide an update here in the README and elsewhere if we do intend to stop maintaining those scripts. 

I hope this answers your question. Let me know if there's anything else I can do to help.
