### ISSUE TITLE
There is an issue on New York State 

### ISSUE THREAD

**Issue by Monesha67** [COVID19Tracking/covid-tracking-data#260]
The system isn’t keeping track on the new variant in New York State. Here’s an article. https://www.governor.ny.gov/news/governor-cuomo-announces-discovery-first-brazilian-variant-new-york-state-resident

**Comment by zachlipton** [comment]
Hi Monesha67. [We ended our daily data collection on March 7th](https://covidtracking.com/analysis-updates/covid-tracking-project-end-march-7) and aren't currently doing any tracking of variant data. New York City has [some datasets on variants ](https://www1.nyc.gov/site/doh/covid/covid-19-data-archive.page) that may be of interest to you.
