### ISSUE TITLE
Current and Cumulative data doesn't make sense?

### ISSUE THREAD

**Issue by MrEManphoto** [COVID19Tracking/covid-tracking-data#38]
Can the Current and Cumulative data for inICU and onVentilator be reviewed/revised?  Cumulative numbers in particular seem suspect ... shouldn't cumulative numbers always either increase or stay the same?

**Comment by davidwilson001** [comment]
![2020-04-08_114407](https://user-images.githubusercontent.com/5106764/78810782-73013f80-798e-11ea-9f47-73abb94b1eeb.jpg)

We are having the same issue with the data.  ICU and Vent numbers appear to be swapped between the "cumulative" and "currently" columns

**Comment by jiecaionline** [comment]
^ bump on this!

**Comment by msmith17** [comment]
Not sure what ^ bump means, but there is some computational error here.  Or I don't understand the column headings.

InIcuCurrently goes up and down, as doe OnVentilatorCurrently.  Makes sense.  But
IncIcuCurrently > InIcuCumulative
OnVentilatorCurrently > OnVentilatorCumulative

**Comment by julia326** [comment]
Hi folks, this data can indeed be counterintuitive but please see the data documentation in https://covidtracking.com/api
