### ISSUE TITLE
importing state 'AS' has different header order than other states.

### ISSUE THREAD

**Issue by AlanJayWeiner** [COVID19Tracking/covid-tracking-data#47]
`=IMPORTDATA("http://covidtracking.com/api/states/daily.csv?state=AS")` gives:
date | state | positive | negative | hash | dateChecked | total | totalTestResults | posNeg | fips | deathIncrease | hospitalizedIncrease | negativeIncrease | positiveIncrease | totalTestResultsIncrease | pending | hospitalizedCurrently | hospitalizedCumulative | inIcuCurrently | inIcuCumulative | onVentilatorCurrently | onVentilatorCumulative | recovered | death | hospitalized |  

All other states give this header order:
`=IMPORTDATA("http://covidtracking.com/api/states/daily.csv?state=AK")` gives:
date | state | positive | negative | pending | hospitalizedCurrently | hospitalizedCumulative | inIcuCurrently | inIcuCumulative | onVentilatorCurrently | onVentilatorCumulative | recovered | hash | dateChecked | death | hospitalized | total | totalTestResults | posNeg | fips | deathIncrease | hospitalizedIncrease | negativeIncrease | positiveIncrease | totalTestResultsIncrease |

**Comment by julia326** [comment]
Hi there, Please use the column names rather than order for data extraction whenever possible
