### ISSUE TITLE
100% positive tests

### ISSUE THREAD

**Issue by AarBee1** [COVID19Tracking/covid-tracking-data#48]
Seems like there are a few (but not insignificant) dates when the number of positive cases in state are equal to the number of total tests. This is likely an error especially for the more recent dates. If you have access to the original webpages from where this data were collected, I would be happy to extract the correct info.

Looking at dates more recent than April 1st. Here is a list of states and dates with such anamolous data:
AL ['2020-04-12', '2020-04-11', '2020-04-10', '2020-04-07']
AZ ['2020-04-05']
CA ['2020-04-13', '2020-04-06']
CO ['2020-04-11']
CT ['2020-04-08']
DE ['2020-04-12', '2020-04-08', '2020-04-06']
HI ['2020-04-07', '2020-04-03']
IA ['2020-04-14']
KS ['2020-04-08']
KY ['2020-04-11', '2020-04-09']
ME ['2020-04-14', '2020-04-12', '2020-04-11', '2020-04-10', '2020-04-09', '2020-04-08', '2020-04-07', '2020-04-06', '2020-04-05', '2020-04-04', '2020-04-03', '2020-04-02']
NJ ['2020-04-13']
NM ['2020-04-11']
OK ['2020-04-13', '2020-04-12', '2020-04-08']
OR ['2020-04-10', '2020-04-04']
MI ['2020-04-09', '2020-04-08']
MS ['2020-04-12', '2020-04-11', '2020-04-10', '2020-04-09', '2020-04-08', '2020-04-07', '2020-04-03']
MO ['2020-04-13']
RI ['2020-04-13', '2020-04-09']
SC ['2020-04-13', '2020-04-06', '2020-04-03']
UT ['2020-04-02']
VT ['2020-04-10']
WA ['2020-04-14', '2020-04-13', '2020-04-12', '2020-04-11', '2020-04-10', '2020-04-09', '2020-04-08', '2020-04-07']
WY ['2020-04-14', '2020-04-12']

Code snippet for the output above:

```
df=pd.read_csv(file, index_col=0,parse_dates=True, infer_datetime_format=True)
cut_off = datetime.date(year=2020,month=4,day=1)
for st in abbrev_list:
    st_data  = df[df['state']==st]
    ind=np.where(st_data['positiveIncrease'] == st_data['totalTestResultsIncrease'])[0]
    dates = [str(d.date()) for d in st_data.index[ind] if d > cut_off]
    if len(dates) > 0:
        print(st, dates)
```

**Comment by julia326** [comment]
Hi folks, we're working through some historical data issues - thank you for heads up!
