### ISSUE TITLE
ICU and hospitalization tracking

### ISSUE THREAD

**Issue by nnoll** [COVID19Tracking/covid-tracking-data#5]
Hey all,

I hope this is the right repo to open this issue, but I was wondering if it was at all possible to aggregate ICU or hospital usage in this data source? We are currently integrating this data into our model at neherlab.org/covid19 and would love to have access to this info.

Thanks!

**Comment by julia326** [comment]
Hi there! We'd be very interested in hospital utilization rates too - folks are discussing how to find that sort of data. If you have any tips on states publishing ICU/hospital utilization rates, please send them my way!

**Comment by StevenLi-DS** [comment]
Data for hospitalization in NY on 3/27/2020 is missing

![image](https://user-images.githubusercontent.com/33796896/77805512-6e688d00-7058-11ea-923b-1adc34ae76a7.png)

am I mssing something?

**Comment by Texas42** [comment]
NY has been. On are reporting for several days now.  Expect something around 1030pm EST as my best guess.

**Comment by jawiv** [comment]
Wanted to follow up on this.

First: Y'all are doing a great job. Thank you!

I happened to catch maybe an accidental glimpse of a new set of datapoints you may be planning to start tracking (currentlyHospitalized, cumulativeHospitalized, currentlyInIcu, cumulativeInIcu, currentlyOnVentilators, cumulativeOnVentilators). Would be a welcome addition!

It looks like there are still states that are not reporting hospitalizations. It might be helpful to include hospitalization data in the overall grade for each state.

**Comment by julia326** [comment]
Hi folks, we're tracking this data now as well - closing this issue but please reopen if more comments or questions.
