### ISSUE TITLE
Screenshots api endpoint not working (404)

### ISSUE THREAD

**Issue by srnelson** [COVID19Tracking/covid-tracking-data#56]
State Website Screenshots - https://covidtracking.com/api/v1/screenshots.json (link from https://covidtracking.com/api) yields:

{"code":404,"error":"404 - NOT FOUND","pathname":"/v1/screenshots.json"}

**Comment by julia326** [comment]
Hi there! This has been fixed - right now, https://covidtracking.com/api links to https://covidtracking.com/api/v1/states/screenshots.json which works.
