### ISSUE TITLE
us_daily.csv is empty

### ISSUE THREAD

**Issue by johnrolfeellis** [COVID19Tracking/covid-tracking-data#58]
"us_daily.csv" contains a single line:

> Redirecting to /api/v1/us/daily.csv

Did I miss an announcement about its demise?  It's still listed here:
https://github.com/COVID19Tracking/covid-tracking-data

**Comment by julia326** [comment]
@johnrolfeellis thanks for catching this! We updated our API links and I just fixed where this repo pulls from - it should auto-update within the next hour, and all the data will be back.

**Comment by johnrolfeellis** [comment]
Excellent, thanks.
