### ISSUE TITLE
Indiana Hospitalizations

### ISSUE THREAD

**Issue by dcorbin** [COVID19Tracking/covid-tracking-data#68]
They showed up only recently, (May 8th).  They have not changed in 8 days, while all other numbers are changing.  I looked at the most recent screen-shot, and I don't see where hospitalized is coming from for Indiana.  The data _looks_ like it's in error to me.

**Comment by julia326** [comment]
Sorry for only addressing this now - this has hopefully been fixed upstream at the source (the Covid Tracking Project API).
