### ISSUE TITLE
Florida did not update for 2 days ...

### ISSUE THREAD

**Issue by pbeerli** [COVID19Tracking/covid-tracking-data#69]
Florida did not update for two days, but I  see now that it caught up except that the data for yesterday is zero and today is higher than the highest ever, I guess these are cumulative values, anyone knows that values for yesterday? [this is about states_daily_4pm_et.csv]

**Comment by julia326** [comment]
Sorry for only addressing now - this is just the backup repo, and this has hopefully been addressed upstream at the data source (the API).
