### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by dinoalcantara** [COVID19Tracking/covid-tracking-data#70]
When I try to run the backup_to_s3.py, I'm getting the error.  Does anybody know why?

\backup_to_s3.py", line 147, in save_url_image_to_path
    raise ValueError(f'Could not retrieve URL: {data_url}')

ValueError: Could not retrieve URL: https://www.cdc.gov/covid-data-tracker/

Thank you.

**Comment by julia326** [comment]
Hi @dinoalcantara , that script is actually part of our internal processes - just curious what you were trying to use it for?
