### ISSUE TITLE
JSON API does not return JSON

### ISSUE THREAD

**Issue by ExperimentalHypothesis** [COVID19Tracking/covid-tracking-data#75]
what is returned is actually not a valid JSON - it is a LIST of JSON objects.. which makes it messy for cross windows/linux app to be parsed using pd.read_json()

on windows it works easily, on linux doesnt and needs to be tweked somehow... 

it would be good it the JSON API actually returned valid JSON, for instance like this:

{ "data":
    [ {..}, {..} the list of jsons.. ]
}

**Comment by kevee** [comment]
Hi, @ExperimentalHypothesis, I [don't think there's anything in the JSON spec](https://www.json.org/json-en.html) precluding us using an array. I would like to move towards a nested object, but we have too many folks using this API for us to make such a change.
