### ISSUE TITLE
IA Screenshots are sometimes missing dashboard

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/covid-tracking-data#80]
You history data screen shots for Iowa on Tuesday, June 2, at 6:33pm as well as reports for Wed. June 3 contain NO DATA.

For references here are links to empty screenshots 
https://covidtracking.com/screenshots/IA/IA-20200602-183322.png
https://covidtracking.com/screenshots/IA/IA-20200603-183421.png

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24gup)

**Comment by julia326** [comment]
Closing this one out; fixed by hard-coding a previously iframed link for IA
