### ISSUE TITLE
Data error in MD data started presenting about a week ago

### ISSUE THREAD

**Issue by flyingsymbols** [COVID19Tracking/covid-tracking-data#86]
In the data for MD here: https://covidtracking.com/data/state/maryland#historical

(and via the API) there's a data error on Mar 16 and Mar 17 that is causing a strange loop in my graph based on the data here: https://flyingsymbols.github.io/arewebeatingcovid19/

**Comment by flyingsymbols** [comment]
I believe the error first started showing up about a week ago (my first update that showed the loop was on 2020-06-12)

**Comment by julia326** [comment]
Sorry for only addressing this now - this has hopefully been fixed upstream at the source (the Covid Tracking Project API). Please feel free to reopen if this is still an issue!
