### ISSUE TITLE
Columns where Current > Cumulative

### ISSUE THREAD

**Issue by philgoetz** [COVID19Tracking/covid-tracking-data#87]
In the US historic-data:

- Every entry in the onVentilatorCumulative is much smaller than the corresponding entry in onVentilatorCurrently.
- inIcuCumulative < inIcuCurrently for 3/26 - 5/28.

**Comment by julia326** [comment]
Sorry for only addressing this now - this has hopefully been fixed upstream at the source (the Covid Tracking Project API). Please feel free to reopen if this is still an issue!
