### ISSUE TITLE
[OK] Oklahoma Screenshots are blank

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/covid-tracking-data#89]
https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/OK/OK-20200724-062307.png

**Comment by julia326** [comment]
Fixed, the last few screenshots contain data

**Comment by julia326** [comment]
Just kidding, it still doesn't work reliably - keeping open until fixed for real

**Comment by julia326** [comment]
It looks fixed. Please reopen if you see this again though!
