### ISSUE TITLE
[KS] Kansas tertiary screenshot needs to click on "Testing Rates" button before capture

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/covid-tracking-data#90]
Before taking this screenshot, we need to click on Testing Rates button

`<div class="tab-button-zone-text" data-test-id="tab-button-zone-text" style="font-family: Nunito Sans; color: rgb(255, 255, 255); font-size: 11pt; font-style: normal; font-weight: normal; text-decoration-line: none;">Testing Rates</div>`

![image](https://user-images.githubusercontent.com/1749380/88554604-b393d000-cff4-11ea-832f-cc37cf3abc8c.png)

**Comment by julia326** [comment]
@muamichali could you update the KS tertiary link to https://public.tableau.com/views/COVID-19TableauVersion2/TestingRates?%3Aembed=y&%3AshowVizHome=no ? That'll get the Testing Rates tab

**Comment by julia326** [comment]
This is fixed, e.g. https://covidtracking.com/screenshots/KS/KS-tertiary-20200915-121302.png
