### ISSUE TITLE
[OR] Primary source screenshots obscured by lightbox

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/covid-tracking-data#91]
The primary source screenshots for OR are obscured by a lightbox. Is there any workaround for that? 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_26ya9)

**Comment by julia326** [comment]
This should be fixed now - will check with the next screenshot script run

**Comment by amandafrench** [comment]
Fantastic! Looks much better at https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/OR/OR-20200728-062233.png
