### ISSUE TITLE
Latest commit `0a155b9` has several "empty" .csv's - API redirect

### ISSUE THREAD

**Issue by marcusrussi** [COVID19Tracking/covid-tracking-data#99]
They refer you to the API, rather than containing the data that is meant to be mirrored. This affects the following files:

- `data/counties.csv`
- `data/states_current.csv`
- `data/states_daily_4pm_et.csv`
- `data/states_info.csv`
- `data/us_current.csv`
- `data/us_daily.csv`

**Comment by gnannig** [comment]
Also impacting me.  API has significant downtime issues through my network, so github is preferred, if time-late, delivery method.

**Comment by marcusrussi** [comment]
This issue has persisted in the latest commits to the `master` branch. For my modeling group, it's very useful to be able to fetch data through GitHub due to its reliability, and even more valuable to be able to tie our model runs' input data to a specific Git commit, rather than a hacked-together log of `curl`s and their timestamps.

**Comment by johnrolfeellis** [comment]
Any updates on this issue? Came back after a 10-day vacation to find many of the .csvs haven't been updated for four days -- are they being decommissioned?

cdc.csv Updating public spreadsheet CSV backups 5 hours ago
cdc_testing.json Updating public spreadsheet CSV backups 5 hours ago
cdc_trend.json Updating public spreadsheet CSV backups 5 hours ago
counties.csv Updating public spreadsheet CSV backups 4 days ago
states_current.csv Updating public spreadsheet CSV backups 3 days ago
states_daily_4pm_et.csv Updating public spreadsheet CSV backups 4 days ago
states_info.csv Updating public spreadsheet CSV backups 4 days ago 
us_current.csv Updating public spreadsheet CSV backups 4 days ago
us_daily.csv Updating public spreadsheet CSV backups 3 days ago

**Comment by johnrolfeellis** [comment]
The COVID19Tracking/covid-tracking-data repository is no longer supported.  The [Readme](https://github.com/COVID19Tracking/covid-tracking-data/blob/master/README.md) says:

"Do not use this repository to download or display data. Use the COVID Tracking API instead."

The CSVs are available in that repository, albeit with somewhat different names.

**Comment by julia326** [comment]
Hi there, this repo in general should not be used as the source of data truth - instead, please use our API at https://covidtracking.com/api. Apologies all for the confusion here!
